######################################################################
# Automatically generated by qmake (3.0) ? 12? 8 10:15:20 2015
######################################################################

TEMPLATE = lib
TARGET = execscriptplugin
INCLUDEPATH += .

QT += quick

# Input
HEADERS += exec-script.h

DESTDIR += ./execScript
CONFIG += c++11 slient
MOC_DIR = ./Intermediate/moc
OBJECTS_DIR = ./Intermediate/obj
